### ISSUE TITLE
API Packages - Implement SQL Hooks On Create+Alter Tables With embedsMany

### ISSUE THREAD

**Issue by slathrop** [vuepointjs/pm#6]
### Notes

- LoopBack MSSQL connector is not respecting datatype (e.g., nvarchar(1000)) of model property/field backing an embedsMany relationship
- The datatype for string fields is always nvarchar(255), which drastically limits the number of embedded connections possible

### Tasks

- [ ] Test ability of SQL hook to intercept DDL
- [ ] Implement logic to determine if DDL matches a model with an embedsMany relation
- [ ] Implement logic to modify SQL DDL command that will be issued so that SQL column datatype is correct
- [ ] Test
